import { readFileSync,writeFileSync } from 'node:fs';
const root='artifacts/sprint7',read=name=>JSON.parse(readFileSync(`${root}/${name}.json`,'utf8'));
const baseline=read('performance-v1'),vector=read('performance-vector'),final=read('performance-v11');
const native=name=>{
 const raw=read(name),peak=raw.samples.reduce((a,b)=>b.privateSumBytes>a.privateSumBytes?b:a),stage=r=>({label:r.label,sampleCount:r.sampleCount,privatePeakBytes:r.privatePeakBytes,workingSetSumPeakBytes:r.workingSetSumPeakBytes,lastPrivateBytes:r.lastNative?.privateSumBytes??null,lastWorkingSetBytes:r.lastNative?.workingSetSumBytes??null,jsHeap:r.heapAfter});
 return{method:raw.method,intervalMs:raw.sampleIntervalMs,peak:{privateBytes:peak.privateSumBytes,workingSetSumBytes:peak.workingSetSumBytes,processRoles:peak.processes.map(({role,privateBytes,workingSetBytes})=>({role,privateBytes,workingSetBytes}))},observations:raw.stages.filter(s=>/baseline|import|export|retained|test-only|unload/.test(s.label)).map(stage)};
};
const toRows=p=>p.results.map(({count,kind,gpxBytes,quality,duration,summary,iterations})=>({count,kind,gpxBytes,quality,duration,summary,codec:iterations.at(-1).codec,video:iterations.at(-1).video}));
const luminance=hex=>{const [r,g,b]=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*r+.7152*g+.0722*b;};
const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
const report={date:'2026-10-09',environment:{os:final.os,browser:final.browser,node:process.version},method:final.method,baselineCommit:'5f39332b7358949d248da6b2f99ba445ee1b41e8',candidateApplicationCommit:read('cinematic/acceptance').sourceCommit,performance:{staticBaseline:toRows(baseline),fullVectorIntermediate:toRows(vector),boundedRouteCache:toRows(final)},memory:{staticBaseline:native('memory-v1'),boundedRouteCache:native('memory-v11'),resourceAudit:read('resource-audit-v11')},examples:read('cinematic/acceptance'),controlledBaseline:read('comparison/controlled-baseline'),compatibility:read('compatibility-v11'),nominalPaletteContrast:{method:'sRGB WCAG luminance ratios of declared solid colours; not a claim that every antialiased video pixel meets that ratio.',atlas:{routeToLand:contrast('#ae421c','#e5e3ce'),routeToWater:contrast('#ae421c','#a9c8ce'),captionToPanel:contrast('#203f43','#f7f3e9')},night:{routeToLand:contrast('#ffd477','#173443'),routeToWater:contrast('#ffd477','#071521'),captionToPanel:contrast('#f4f3e8','#0b1b2b')}},limitations:['Single Windows machine; repeated performance and four memory cycles, not a universal benchmark.','Canvas timing is CPU submission, not displayed FPS/GPU completion.','Native values are sampled process sums; working sets can double-count shared pages.','GPU VRAM and dedicated codec memory unmeasured.','Physical mobile and Safari NOT TESTED.','Natural Earth is generalised and has no street/terrain data.','Owner visual approval pending; no audience-retention study.']};
const visual=read('visual-v11');report.visualGeometry={configurations:visual.length,frames:visual.reduce((n,r)=>n+r.frames.length,0),overflows:visual.filter(r=>r.overflow.length).length,endpointOverlaps:visual.filter(r=>r.overlaps.length).length,method:'64 synthetic geometry/style/quality/aspect configurations; six timestamps each, including segment transition. Measured text bounding boxes, not physical-phone usability.'};
const production=JSON.parse(readFileSync('artifacts/release/acceptance-local-smoke.json','utf8'));report.productionSmoke={status:production.status,scope:production.scope,sourceCommit:production.sourceCommit,version:production.version,publicHttps:production.publicHttps,packageBytes:production.packageBytes,packageHashesVerified:production.packageHashesVerified,csp:production.csp,privacy:production.privacy,cancelAndRecovery:production.cancelAndRecovery,unsupportedEncoder:production.unsupportedEncoder,outputs:production.outputs.map(({video})=>video)};
writeFileSync('docs/CINEMATIC_EVIDENCE.json',JSON.stringify(report,null,2)+'\n');
console.log('Written public synthetic-only summary; raw process PIDs/samples remain ignored.');
