import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {validateImagery,imageryUV,imageryCoversTerrain,imageryDetailWeight} from '../../src/imagery';
import {TerrainDataset} from '../../src/terrain';
import {validateStoryConfig,defaultStoryConfig} from '../../src/story';
const manifest=JSON.parse(readFileSync('public/imagery/sogne-sentinel.json','utf8'));
describe('reviewed georeferenced photographic terrain',()=>{
 it('verifies real source crop provenance and bounded derivative checksum',()=>{const m=validateImagery(manifest),bytes=readFileSync('public/imagery/'+m.file);expect(bytes.length).toBe(m.bytes);expect(createHash('sha256').update(bytes).digest('hex')).toBe(m.sha256);expect(manifest.sources).toHaveLength(2);for(const s of manifest.sources)for(const a of s.assets)expect(a.cropSha256).toMatch(/^[a-f0-9]{64}$/);expect(manifest.coveragePixels).toBe(m.width*m.height);expect(Object.isFrozen(m.bounds)).toBe(true);});
 it('maps north/south/east/west and pixel centres without mirrored imagery',()=>{expect(imageryUV(manifest,[-15000,20000])).toEqual([0,0]);expect(imageryUV(manifest,[15000,-20000])).toEqual([1,1]);expect(imageryUV(manifest,[0,0])).toEqual([.5,.5]);const [u,v]=imageryUV(manifest,[-14980,19980]);expect(u).toBeCloseTo(.5/750);expect(v).toBeCloseTo(.5/1000);expect(imageryUV(manifest.detail,[-8000,8000])).toEqual([0,0]);expect(imageryUV(manifest.detail,[5000,-8000])).toEqual([1,1]);expect(()=>imageryUV(manifest,[NaN,0])).toThrow();});
 it('retains the exact reviewed20m prototype for an honest comparison',()=>{const bytes=readFileSync('public/imagery/sogne-sentinel-20m.jpg');expect(bytes.length).toBe(1127607);expect(createHash('sha256').update(bytes).digest('hex')).toBe('521cddcd174a3d3a3208d9008293287040a1d866d7c755fadbfb5a8a794185ec');});
 it('pins both real LODs, caps aggregate pixels/bytes and validates patch coverage',()=>{const m=validateImagery(manifest),fine=m.detail!;for(const level of [m,fine]){const bytes=readFileSync('public/imagery/'+level.file);expect(bytes.length).toBe(level.bytes);expect(createHash('sha256').update(bytes).digest('hex')).toBe(level.sha256);}expect(m.width*m.height+fine.width*fine.height).toBe(2830000);expect(m.bytes+fine.bytes).toBe(997049);for(const detail of [{...fine,detail:fine},{...fine,origin:[0,0]},{...fine,bounds:[-18000,-8000,-5000,8000]},{...fine,bytes:2000000}])expect(()=>validateImagery({...m,detail})).toThrow();});
 it('selects bounded, smooth, deterministic scale detail and honest coarse fallback',()=>{const weights=[600,1200,3000,12000,40000].map(d=>imageryDetailWeight(manifest,d,46,720));expect(weights[0]).toBe(1);expect(weights.at(-1)).toBe(0);expect(weights.every((w,i)=>w>=0&&w<=1&&(i===0||w<=weights[i-1]))).toBe(true);const before=imageryDetailWeight(manifest,15000,46,720);imageryDetailWeight(manifest,1000,46,720);expect(imageryDetailWeight(manifest,15000,46,720)).toBe(before);expect(imageryDetailWeight(manifest,15000.01,46,720)-before).toBeLessThan(.00001);expect(imageryDetailWeight(manifest,1000,46,720,false)).toBe(0);expect(imageryDetailWeight({...manifest,detail:undefined},1000,46,720)).toBe(0);expect(()=>imageryDetailWeight(manifest,NaN,46,720)).toThrow();});
 it.each([{width:30000},{height:Infinity},{bytes:3*1024*1024},{file:'https://untrusted/image.jpg'},{bounds:[0,0,0,1]},{origin:[NaN,60]},{sha256:'z'.repeat(64)},{attribution:'unknown'},{spacingMeters:10}])('rejects unbounded, unreviewed or misaligned input %j',override=>expect(()=>validateImagery({...manifest,...override})).toThrow());
 it('requires entire mesh coverage and the same geographic origin',()=>{const m=JSON.parse(readFileSync('public/terrain/sogne.json','utf8')),l=m.lods[1],t=new TerrainDataset(m,l,new Int16Array(readFileSync('public/terrain/'+l.file).buffer.slice(0)));expect(imageryCoversTerrain(manifest,t)).toBe(true);expect(imageryCoversTerrain({...manifest,origin:[6,61.28]},t)).toBe(false);expect(imageryCoversTerrain({...manifest,bounds:[-15000,-20000,10000,20000]},t)).toBe(false);});
 it('keeps surface selection in the immutable export snapshot and rejects arbitrary modes',()=>{const c=validateStoryConfig({...defaultStoryConfig(),terrainSurface:'photo'});expect(c.terrainSurface).toBe('photo');expect(Object.isFrozen(c)).toBe(true);expect(()=>validateStoryConfig({...c,terrainSurface:'arbitrary' as 'photo'})).toThrow();});
});
