import {describe,it,expect} from 'vitest';
import {TerrainDataset,type TerrainManifest} from '../../src/terrain';
import {createTerrainCameraPlan,getTerrainCameraStateAt,requiredVisibleAltitude,projectTerrainPoint} from '../../src/terrain-camera';
import {StoryTimeline} from '../../src/timeline';
import {defaultStoryConfig} from '../../src/story';
import {routeMetrics} from '../../src/geo';
import type {Route,RoutePoint} from '../../src/route';
function fixture(shape:(x:number,y:number)=>number=()=>500,origin:[number,number]=[6.2,61.28]){
 const level={file:'test.i16',spacingMeters:100,width:201,height:201,bytes:80802,sha256:'test',noDataCount:0};
 const manifest:TerrainManifest={id:'synthetic',origin,westMeters:-10000,southMeters:-10000,eastMeters:10000,northMeters:10000,lods:[level],noData:-32768,minElevation:0,maxElevation:1500,verticalScale:1,units:'metres',verticalDatum:'synthetic fixture',sourceCrs:'synthetic',sourceResolutionMeters:100,attribution:'synthetic'};
 return new TerrainDataset(manifest,level,Int16Array.from({length:201*201},(_,i)=>shape((i%201)*100-10000,Math.floor(i/201)*100-10000)));
}
function route(t:TerrainDataset,segments:number[][][]):Route{const points=segments.map(s=>s.map(p=>({...t.geographic([p[0],p[1]]),elevation:123})));return {segments:points,...routeMetrics(points),name:'Synthetic'};}
describe('bounded real terrain model',()=>{
 it('bilinear sampling and exact triangle draping keep GPX elevation separate',()=>{const t=fixture((x,y)=>1000+x*.02+y*.01);expect(t.sampleXY([125,225])).toBeCloseTo(1004.75);expect(t.meshElevation([125,225])).toBeCloseTo(1004.75);const p={...t.geographic([125,225]),elevation:77};expect(t.sampleElevation(p.lat,p.lon)).toBeCloseTo(1004.75);expect(p.elevation).toBe(77);expect(t.sampleXY([10001,0])).toBeUndefined();});
 it('does not fill no-data with zero or interpolate across it',()=>{const t=fixture();t.heights[100*201+100]=-32768;expect(t.sampleXY([1,1])).toBeUndefined();expect(t.meshElevation([1,1])).toBeUndefined();expect(t.ceiling([1,1])).toBeUndefined();expect(t.getTerrainCoverage().noDataSamples).toBe(1);});
 it('rejects corrupt dimensions, unbounded resolution and extreme elevations',()=>{const t=fixture();expect(()=>new TerrainDataset(t.manifest,{...t.level,width:99999},t.heights)).toThrow();t.heights[0]=10000;expect(()=>new TerrainDataset(t.manifest,t.level,t.heights)).toThrow();});
 it('uses the short antimeridian arc and finite high-latitude local coordinates',()=>{const t=fixture(()=>200,[179.98,80]);const p={lon:-179.98,lat:80.01};const xy=t.world(p);expect(xy[0]).toBeGreaterThan(0);expect(xy[0]).toBeLessThan(1000);expect(t.geographic(xy).lon).toBeCloseTo(p.lon);expect(t.sampleXY(xy)).toBe(200);});
 it('rejects uncovered edges and holes even when endpoints are valid',()=>{const t=fixture();t.heights[100*201+100]=-32768;const r=route(t,[[[-2000,0],[2000,0]]]);expect(t.routeCoverage(r)).toBe(false);expect(()=>createTerrainCameraPlan(new StoryTimeline(r,defaultStoryConfig()),t,720,1280)).toThrow();});
});
describe('pure terrain camera and conservative flight envelope',()=>{
 for(const duration of [10,20,30] as const)for(const aspect of [[1280,720],[720,1280]])it(`deterministic ${duration}s ${aspect.join('x')} overview/follow/reveal`,()=>{
  const t=fixture((x,y)=>Math.round(600+700*Math.exp(-((x-1000)**2+(y-500)**2)/900000))),r=route(t,[[[-4500,-3500],[-1000,-500],[1800,2000],[4500,3500]]]),timeline=new StoryTimeline(r,{...defaultStoryConfig(),durationSeconds:duration}),plan=createTerrainCameraPlan(timeline,t,...aspect as [number,number]);
  const middle=getTerrainCameraStateAt(duration/2,plan);getTerrainCameraStateAt(duration-1,plan);expect(getTerrainCameraStateAt(duration/2,plan)).toEqual(middle);
  expect(getTerrainCameraStateAt(0,plan).position).toEqual(getTerrainCameraStateAt(duration,plan).position);expect(getTerrainCameraStateAt(0,plan).position[2]).toBeGreaterThan(middle.position[2]*1.5);
  for(let time=0;time<=duration;time+=duration/120){const c=getTerrainCameraStateAt(time,plan);expect([...c.position,...c.target,c.pitch,c.bearing,c.clearance].every(Number.isFinite)).toBe(true);expect(c.clearance).toBeGreaterThanOrEqual(349.99);expect(c.position[2]).toBeGreaterThanOrEqual(t.max+350);expect(requiredVisibleAltitude(t,c.position,c.target)).toBeCloseTo(c.position[2],6);expect(c.roll).toBe(0);}
 });
 it('cuts disconnected segments rather than flying a fictitious path between them',()=>{const t=fixture(),r=route(t,[[[-5000,-3000],[-3000,-3000]],[[3000,3000],[5000,3000]]]),timeline=new StoryTimeline(r,defaultStoryConfig()),plan=createTerrainCameraPlan(timeline,t,1280,720),cut=2+16*timeline.path.edges[1].start/timeline.path.total,before=getTerrainCameraStateAt(cut-.001,plan),after=getTerrainCameraStateAt(cut+.001,plan);expect(before.segment).toBe(0);expect(after.segment).toBe(1);expect(before.target[1]).toBeCloseTo(-3000);expect(after.target[1]).toBeCloseTo(3000);expect(timeline.at(cut).markerOpacity).toBeLessThan(.01);});
 it('stationary/duplicate points remain finite and never divide by zero',()=>{const t=fixture(),r=route(t,[[[0,0],[0,0],[0,0]]]),plan=createTerrainCameraPlan(new StoryTimeline(r,defaultStoryConfig()),t,720,1280);for(const seconds of [0,2,10,18,20])expect(getTerrainCameraStateAt(seconds,plan).position.every(Number.isFinite)).toBe(true);});
 for(const name of ['cliff','valley','pass','fjord','sharp ridge'])it(`trajectory and independent dense LOS remain above ${name}`,()=>{const t=fixture((x,y)=>name==='cliff'?(x>0?1600:0):name==='valley'?Math.round(1400*(1-Math.exp(-x*x/400000))):name==='fjord'?(Math.abs(y)<500?0:1200):name==='pass'?Math.round(1600*Math.exp(-x*x/1000000)*(1-.8*Math.exp(-y*y/200000))):Math.round(1600*Math.exp(-x*x/200000))),r=route(t,[[[-4000,-3500],[-1000,-1000],[1000,500],[4000,3500]]]),plan=createTerrainCameraPlan(new StoryTimeline(r,defaultStoryConfig()),t,720,1280);for(let time=0;time<=20;time+=.1){const c=getTerrainCameraStateAt(time,plan);expect(c.position[2]).toBeGreaterThanOrEqual(t.max+350);expect(c.position[2]).toBeLessThan(80000);expect(c.target[2]).toBeGreaterThanOrEqual(t.meshElevation([c.target[0],c.target[1]])!+23.999);for(let i=0;i<=500;i++){const f=i/500,xy:[number,number]=[c.target[0]+(c.position[0]-c.target[0])*f,c.target[1]+(c.position[1]-c.target[1])*f],ray=c.target[2]+(c.position[2]-c.target[2])*f;expect(ray-t.meshElevation(xy)!).toBeGreaterThanOrEqual(-.000001);}}});
 it('matches caption-safe perspective framing for an elevated overview',()=>{const t=fixture((x,y)=>Math.round(500+500*Math.exp(-y*y/2000000))),r=route(t,[[[-4500,-3500],[0,0],[4500,3500]]]);for(const [w,h] of [[1280,720],[720,1280]]){const plan=createTerrainCameraPlan(new StoryTimeline(r,defaultStoryConfig()),t,w,h),camera=getTerrainCameraStateAt(0,plan);for(const p of r.segments[0]){const xy=t.world(p),[x,y]=projectTerrainPoint([...xy,t.meshElevation(xy)!+24],camera.position,camera.target,w,h);expect(x).toBeGreaterThan(Math.min(w,h)*.075);expect(x).toBeLessThan(w-Math.min(w,h)*.075);expect(y).toBeGreaterThan(Math.min(w,h)*.22);expect(y).toBeLessThan(h-Math.min(w,h)*.28);}}});
});
